---
- name: Install apache and check service state
  hosts: all
  become: yes

  tasks:
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: latest # optional, latest is the default

  - name: Enable service httpd, and not touch the state
    service:
      name: httpd
      enabled: yes

  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started

