---
- name: set up ssh keys
  hosts: all
  become: true

  tasks:
  - name: Deploy SSH Public Key
    authorized_key:
      user: ansible
      state: present
      key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
